name: "portainer"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - traefik
    volumes:
      - "portainer_data:/data"  # Монтируем том для хранения данных Portainer
      - "/var/run/docker.sock:/var/run/docker.sock"  # Доступ к Docker демону
    labels:
      - "traefik.enable=true"                                      # Включаем Traefik для Portainer
      - "traefik.http.routers.portainer.rule=Host(`portainer.kowlad.ru`)"  # Домен для доступа к Portainer
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"   # Порт Portainer внутри контейнера
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=leresolver"
    restart: unless-stopped

networks:
  traefik:
    external: true

volumes:
  portainer_data:  # Здесь хранится вся информация о Portainer